### ISSUE TITLE
how to use inclusion in sonarqube

### ISSUE THREAD

**Issue by Mydaymatt** [SonarSource/SonarJS#1140]
<As i got error in using exclusion property, (saying exclusion=null)

Some one please help me on using inclusion property for sonarqube as a jenkins pipeline

**Comment by andrea-guarino-sonarsource** [comment]
Hi @Mydaymatt,
You should be able to find all the information about inclusion/exclusion in SonarQube [here](https://docs.sonarqube.org/7.4/project-administration/narrowing-the-focus/).

However, since your question is not related to SonarJS itself, could you please post your question in our [community forum](https://community.sonarsource.com/)?

Please, make sure to include more information (SQ version, are you using sonar-scanner?, logs, ...) and specify what's your usecase.
