### ISSUE TITLE
 Add rule S1192 (based on 'eslint-plugin-sonarjs/no-duplicate-string') for TS

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#1371]
Rule is already covered for JS

**Comment by quentin-jaquier-sonarsource** [comment]
### Changes in the rule
- String is now trimmed before being checked for duplicate.
This may add issues, or remove others that falls under the length threshold.
- We now [ignore object property keys](https://github.com/SonarSource/eslint-plugin-sonarjs/blob/b6b03ec6f4d9b430abea6459c95579ba8a8c0037/src/rules/no-duplicate-string.ts#L89).

These two changes may also change the line on which the issue is reported.
