### ISSUE TITLE
Add rule S1526 ('no-variable-usage-before-declaration') for TS/JS

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#1419]

**Comment by quentin-jaquier-sonarsource** [comment]
### Changes in the rule
- We are now reporting on `const` and `let` variables used before declaration 
- We are now reporting an issue on all usages (and not once per symbol).
- We are now reporting Classes and Enums used before declaration (only if outside of a function scope).

**Comment by vilchik-elena** [comment]
Reverted and renamed to `Add rule S1526 ('no-variable-usage-before-declaration' in tslint) for TS/JS`

**Comment by quentin-jaquier-sonarsource** [comment]
Due to the revert, we lost the matching between the implementation behavior, and the [RSPEC](https://jira.sonarsource.com/browse/RSPEC-1526) description.

When tackling this ticket, make sure that the title (for sub-tasks JS and TS), match the implemented behavior.

**Comment by nicolas-harraudeau-sonarsource** [comment]
IMHO we shouldn't try to detect `let`, `const`, `class` or `enum` with this rule. Using them before declaring them will result in a bug, whereas S1526 is a code-smell rule because using a variable declared with `var` before it is used works but is confusing.

We already have S3827 which raises an issue when a variable is undefined. We could later extend it to take into account `let` and `const` variable, as well as classes and enums.

Does it make sense?
