### ISSUE TITLE
Add rule S1656 (based on 'no-self-assign') for TS/JS

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#1427]

**Comment by quentin-jaquier-sonarsource** [comment]
### Changes in the rule

* eslint implementation doesn't consider mutating functions on arrays `sort` and `reverse`, ie. `a = a.sort()` is not raised
* eslint implementations detects equivalent expressions which differ due to parenthesis `a = (a)`
* `no-self-assign` doesn't handle member expressions using `this`, so  `this.x = this.x` is not detected
