### ISSUE TITLE
Add rule S3699 (based on 'eslint-plugin-sonarjs/no-use-of-empty-return-value') for TS

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#1452]

**Comment by quentin-jaquier-sonarsource** [comment]
### Changes in the rule

For TS, the rule is no longer relying on type. 
This is not critical since the old implementation faced FPs related to Promises, however, this rule could still benefit from the wise use of type information. An [issue](https://github.com/SonarSource/eslint-plugin-sonarjs/issues/124) in eslint-plugin-sonarjs is here to improve this rule.
