### ISSUE TITLE
Rule S5689 Recovering fingerprints from web application technologies should not be possible

### ISSUE THREAD

**Issue by eric-therond-sonarsource** [SonarSource/SonarJS#1836]
Implements [RSPEC-5689](https://jira.sonarsource.com/browse/RSPEC-5689)

For both JS/TS

Code examples: https://github.com/SonarSource/security-expected-issues/tree/master/javascript/rules/vulnerabilities/RSPEC-5689

Express.js app is considered safe if any of the following is executed:
```
app.disable("x-powered-by");
```
or 
```
let hidePoweredBy = require('hide-powered-by'); 
app.use(hidePoweredBy());
```

Report on the `app.express()` instantiation if both are missing

**Comment by andrey-tyukin-sonarsource** [comment]
As of now, the rule has been implemented with two additional changes:

 1. The [`helmet` middleware](http://expressjs.com/en/advanced/best-practice-security.html#use-helmet) (which includes `hidePoweredBy` as its subcomponent) is also sufficient, the rule doesn't raise any issues if `app.use(helmet())` occurs somewhere.
 2. The `app.disable('header')` is the same as `app.set('header', false)`, so we also handle the `set`-method invocations.

As inspiration for further improvements:

 3. `app.use(helmet.hidePoweredBy())` might be more probable than the standalone `app.use(hidePoweredBy())`, simply because `helmet` is so much easier to remember, and it's also easier to let `.hidePoweredBy()` by handled by autocompletion that to type it out.
 4. `res.removeHeader("x-powered-by");` or `res.setHeader('x-powered-by', 'some-easter-egg-nonsense')` would also have been sufficient, and it's [circulating online as a possible solution](https://blog.praveen.science/getting-rid-of-the-x-powered-by-in-express-js-middle-ware-using-blood-sweat/).
 5. `helmet` has options, which might deactivate this particular middleware. It should not produce any FPs, though, only FNs.

A general remark:

This rule is attempting to collect ["evidence of absense"](https://en.wikipedia.org/wiki/Evidence_of_absence), i.e. it raises issues if it *fails to find certain constructs*. Rules of this type tend to be brittle, because we are blaming user's code for our failure to find something. We might consider deactivating it by default.

**Comment by eric-therond-sonarsource** [comment]
Nice improvements @andrey-tyukin-sonarsource 

We can add `app.use(helmet())` / `app.use(helmet.hidePoweredBy())` to the compliant solution in [the rule description](https://jira.sonarsource.com/browse/RSPEC-5690), it seems to be the standard way to be secure.

I think I miss the main bad pattern to detect, if a developer do:
`res.setHeader('x-powered-by', 'my-technology')` we should raise an issue
of course, as you said a developer can hide the technologies he uses with:
`res.setHeader('x-powered-by', 'random-nonsense')`
but setting  an unnecessary header in the HTTP response is still a bad practice for me, so we are right to raise an issue in this case too and recommend to disable/remove this header (eg:  `res.removeHeader("x-powered-by");`).

WDYT?


About "_evidence of absence_" type of rules and deactivating them by default, we have a lot of rules in this case, it's kind of related to the FP/FN rates that we want to have:

* rules that are triggered when a specific pattern in the code is not found can lead to more FPs and therefore less FNs, for instance with "_injection rules_" we raise an issue if SonarSecurity fails to find a correct sanitizer, so it forces us to maintain the rule over time by continually adding new sanitizers (based on user feedback or not).

* rules that are triggered when a specific pattern is found lead to a very low FP rate but a high FN rate because they are triggered only on what we identified (when first specifying the rule) to be bad development practices, it can lead to a false sense of code security/quality on the user side ("_my code is secure because the SXXXX rule is not triggered but in fact it's just because this rule fails to detect all bad development practices_")

In the case of this rule and express.js, at this moment, we could have at maximum one FP by analyzed project/express.js application, because the issue is raised only once on the express.js instantiation `var app = express()` when `x-powered-by` header is not disabled, so it is not a noisy rule, I think we can give it a chance and improve it over time.

Eric

**Comment by andrey-tyukin-sonarsource** [comment]
1. Added support for `app.use(helmet.hidePoweredBy())`; Also, made `app.use` accept varargs and arbitrarily nested arrays of middlewares.
  2. Did not attempt to track down `res.setHeader('x-powered-by', 'random-nonsense')`, because if neither `helmet` nor `hidePoweredBy` nor `disable` is used, then we report an issue, and if either `helmet` or `hidePoweredBy` is activated, the header is removed anyway. It's not of type "evidence of protecting middleware usage", so it doesn't seem to influence the outcome of the check. Also, this would have to be used in custom user-defined middleware, which is even less likely to end up in same file as the `app`-instantiation.
  3. I understand the impact of "evidence of absence"-type rules on FPs. I've added an additional "escape check": if `app` ends up as parameter to some kind of function, as in `configureMiddleware(app)`, then we deactivate this check entirely. This should (hopefully) reduce the FP rate somewhat. At least it helped with one case in integration tests.
  4. The issue is reported once, but there a lots of similar headers. If dozen of similar "we-couldn't-find-X"-type of issues are raised on every `app` every time, it might be distracting.

I guess we'll have to see how it works out in practice.
