### ISSUE TITLE
Support wildcard patterns for sonar.typescript.tsconfigPath(s)

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#1954]
When using default name `tsconfig.json` we will recursively search for all `tsconfig.json` files in the project. However, if project uses different naming convention, property `sonar.typescript.tsconfigPath` allows to configure only single file.

We should support wildcard pattern in this property to allow using different naming convention, e.g.
`sonar.typescript.tsconfigPath=**/tsconfig.settings.json` 
We should also allow multiple files delimited by comma (similar to sonar.sources)
`sonar.typescript.tsconfigPath=first.tsconfig.json,another.tsconfig.json`

We can consider changing the property name to plural form to reflect the fact that it accepts multiple files.

**Comment by saberduck** [comment]
Related to https://services.sonarsource.com/browse/SUPPORT-16890 (internal link)

**Comment by Frenemy2020** [comment]
Is there any update on this enhancement?

**Comment by escalonn** [comment]
this is a blocker for getting good analysis of a typical Angular 10 project, since several tsconfig files are in play. as it is, you have to choose between getting analysis for your app code (tsconfig.app.json), your test specs (tsconfig.spec.json), and your e2e test code (e2e/tsconfig.json).

the template now uses a new "solution-style" tsconfig.json, but i'm not sure if the scanner can do anything useful with that or not.

**Comment by AlexanderOpran** [comment]
I have pretty much the same issue as @escalonn, I cannot get Sonar to analyze an Angular 10 project at all, even if pointing directly to the tsconfig.app.json. It seems that it is unable to parse the entry points and as such it only analyzes the main.ts and polyfills.ts.

https://community.sonarsource.com/t/sonarts-skipping-files-with-no-tsconfig-json/28231

**Comment by escalonn** [comment]
@AlexanderOpran it works for a new templated angular 10 project, if you revert the tsconfig structure to what is default for angular 9. [Here](https://github.com/2006-jun15-net/nick-project2-kitchen-site/pull/2) is an example PR; note that it also modifies some of the strict TS options.

but note that TS 3.9 is still unsupported by SonarJS, but at the same time it's the minimum required version for Angular 10.

**Comment by alok0914** [comment]
try using sonar.typescript.tsconfigPath=tsconfig.base.json, worked for me.

**Comment by JohannesBe** [comment]
Second this. 

Since Angular 10 breaks automatic tsconfig.json detection (
![image](https://user-images.githubusercontent.com/21303311/91420702-54281a80-e855-11ea-8e34-b74000c6f696.png)
) and now requires a workaround, it is now impossible for me to cover two separate angular projects in one scan. In the past the scanner did the heavy lifting by walking the files, but now that I have to provide `sonar.typescript.tsconfigPath` I am unable to get sonar to work for two angular projects. 

For me comma separation would suffice, although regexing would probably be a more complete solution.

**Comment by KevinChenTR** [comment]
Is the problem in https://community.sonarsource.com/t/cannot-scan-typescript-files-in-angular-monorepo/32407 related to this issue?

**Comment by joe-tingsanchali-sonarsource** [comment]
Another request from a commercial support customer: https://services.sonarsource.com/browse/SUPPORT-34180 (internal link)

**Comment by gabriel-vivas-sonarsource** [comment]
Supporting wildcards and multiple files rely on configuration, which is good for edge cases.
I think we should also and more importantly strive to make analysis work by default for the most common patterns. Here I tried to collect some of them, in order of prevalence.

## Common patterns

Here are some common patterns that I think we should try to support by default:

1. From TypeScript documentation, the basic pattern is to have a config file at the root of the project. It can also be present in a parent but I don't think this applies to Sonar.
Source: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

```
./tsconfig.json
./jsconfig.json
```

2. Since TypeScript 3.9, it is also normal to have multiple config files at the project root without a parent. For example `tsconfig.spec.json`, `tsconfig.app.json`, `tsconfig.shared.json`, etc
Source: https://devblogs.microsoft.com/typescript/announcing-typescript-3-9/#solution-style-tsconfig

```
./tsconfig.*.json
./jsconfig.*.json
```

Some specific examples are used for popular build systems.
Source: https://nx.dev/getting-started/intro

```
./tsconfig.json
./tsconfig.lib.json
./tsconfig.base.json
```

3. There is a common pattern for monorepos, where there would be a config file per first-level child.
Some examples from the community:
* https://community.sonarsource.com/t/typescript-files-not-analyzed-in-new-project/67050
* https://community.sonarsource.com/t/sonarcloud-automatic-analysis-typescript-loc-ignored/71506/7

```
./*/tsconfig.json
./*/jsconfig.json
```

## Common workaround
Some users workaround this by adding a root `tsconfig.json` with the content:
```
{ "include": ["**/*.ts", "**/*.tsx"] }
```

## Related issue
We might consider also fixing this related issue that comes up when people are trying to get their config to work with Sonar: https://github.com/SonarSource/SonarJS/issues/3034

**Comment by gabriel-vivas-sonarsource** [comment]
To better track this, we will limit this ticket to the wildcard and multiple options.
We will create another issue for better support for the common patterns outlined above.
