### ISSUE TITLE
Support "solution" tsconfigs

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#2051]
Reported in https://community.sonarsource.com/t/typescript-tsconfig-json-detection-fundamentally-broken/28893 and https://community.sonarsource.com/t/ts-skipping-files-with-no-tsconfig-json/28231/11

https://devblogs.microsoft.com/typescript/announcing-typescript-3-9/#solution-style-tsconfig

**Comment by vilchik-elena** [comment]
In #1954  there is some discussion about Angular 10 and TS 3.9 solution tsconfigs

**Comment by mboughaba** [comment]
As a workaround for angular 10 project one could change the `sonar.typescript.tsconfigPath` in the properties file to reference the base tsconfig instead of the solution tsconfig.

```
sonar.typescript.tsconfigPath=tsconfig.base.json
```

**Comment by belyaev-alexey** [comment]
> As a workaround for angular 10 projects, one could change the `sonar.typescript.tsconfigPath` in the properties file to reference the base tsconfig instead of the solution tsconfig.
> 
> ```
> sonar.typescript.tsconfigPath=tsconfig.base.json
> ```

It doesn't work for me. I try to add this property to my config and i have this property in line :
-Dsonar.typescript.tsconfigPath=tsconfig.base.json

but i still have same error:
ERROR: Failed to find a source file matching path /routes/frontend/src/test.ts in program created with /routes/frontend/tsconfig.json

**Comment by chriswininger** [comment]
I thought it might be worth sharing a potential workaround that seems to be working for me. I create a special tsoncofig, `tsconfig.sonar.json` and point sonarqube explicitly to that. In the file I put

```
/*
  This is tsconfig is not used for compilation. It is here to support sonarqube.
*/
{
  "extends": "./tsconfig.base.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "rootDir": "src"
  }
}
```

I think one of the keys is inheriting the base and including the rootDir

**Comment by vladonemo** [comment]
We are using SonarQube 8.5.1 that bundles the SonarJS 6.5.0. And still the sensor excludes the files from the analysis:
```

INFO: Sensor TypeScript analysis [javascript]
INFO: Found 2 tsconfig.json file(s): [/home/vsts/work/1/s/tsconfig.json, /home/vsts/work/1/s/e2e/tsconfig.json]
INFO: 171 source files to be analyzed
INFO: Skipping 168 files with no tsconfig.json
INFO: Analyzing 2 files using tsconfig: /home/vsts/work/1/s/tsconfig.app.json
INFO: Version of TypeScript used during analysis: 3.8.3
INFO: Analyzing 1 files using tsconfig: /home/vsts/work/1/s/tsconfig.spec.json
INFO: 171/171 source files have been analyzed
INFO: Sensor TypeScript analysis [javascript] (done) | time=6646ms
```

**Comment by thw0rted** [comment]
I know it's been a long time since there was movement on this issue, but I'm running into tsconfig problems today.  (Sonar server 8.9.8, scanner  4.7.0.2747.)

I have a "solution style" `tsconfig.json`, which points to a number of other configs like `tsconfig.dev.json`, `tsconfig.test.json`, etc.    I'm pretty sure the solution is being parsed correctly, because several of the dev/test/etc configs have 3 entries in the `files` array (`main.ts`, `foo.ts`, `bar.ts`), and I do get analysis of those 3 files.  However, I do not get analysis of any of the files that are imported by those files.  The scanner says "Skipping 363 files with no tsconfig.json" (out of 366).  On the server, I can open the Code tab, browse the tree, and see those 3 files have a line count.  All other `.ts` files have "---" under the line count column.

I tried @chriswininger 's suggestion of creating a separate `tsconfig.sonar.json` with a `rootDir`, but this made no difference.  I changed that config to use `"include": ["src/**/*"]`, and now the scanner says `Analyzing 366 files using tsconfig: path/to/myproject/tsconfig.sonar.json`.  I now have hundreds of new flagged issues that were not there previously.

Is this how it's supposed to work?  I haven't seen anybody discussing a separate tsconfig using `include` anywhere else.
