### ISSUE TITLE
Cognitive Complexity rule consider Angular Controller declaration

### ISSUE THREAD

**Issue by wmeg-aprico** [SonarSource/SonarJS#2470]
Dear Support,

We using SonarQube Version 8.4.1 for source code analysis.
AngularJS controllers are flagged for high cognitive complexity. In fact, we noticed that complexity is computed starting from the root function declaration. 
We estimate that it would be better to compute the complexity for each inner function declared in the controller.
Is there any way to configure SonarScanner to compute cognitive complexity for the methods Inside the controller ? If it is not the case, do you recommend any approach to ignore this issue ?

hank you in advance.
Best Regards.

**Comment by saberduck** [comment]
hello @wmeg-aprico ,

thank you for your feedback. Pls note this is not official support channel, if you require official support, you should contact your sales representative.

Your issue seems to be similar to https://github.com/SonarSource/SonarJS/issues/2238 . Currently there is no way to change the behavior of cognitive complexity rule for angular.

You can exclude cognitive complexity rule for angular controllers, see doc here https://docs.sonarqube.org/latest/project-administration/narrowing-the-focus/

**Comment by wmeg-aprico** [comment]
Dear @saberduck 

Thank you for your response.

Best Regards.
Wael
