### ISSUE TITLE
Integrate CSS analysis from sonar-css

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#2854]
sonar-css plugin uses the same architecture as our JS analyzer. It would make sense to integrate CSS sensor into the JS plugin to ease maintenance effort.

**Comment by jblievremont** [comment]
What is the expected impact of such a move from a product point of view, especially in SonarLint (which currently does not support analysis of CSS in any flavor)?

Would it make sense to also merge the HTML analyzer and offer a one stop shop for all things front end (and make analysis of e.g Vue files way easier)?

**Comment by vilchik-elena** [comment]
@jblievremont we just discussed that we will try to keep impact limited and disable CSS sensor in SonarLint for now. We will consider properly enabling it in some future sprint.

I am not sure about HTML as the motivation for CSS is mostly technical (analysis in NodeJS process).

**Comment by jblievremont** [comment]
Merging the CSS and JS/TS analyzers looks to me like a purely technical move that does not deliver any user-facing value, and yet _could_ have a huge (beneficial) functional impact, completely aligned with our mission to help developers write clean code, if we are truly intentional about it.

Said otherwise, I understand that it kind of makes sense from a purely technical point of view, and I believe that it lacks a strong and clear "why".

**Comment by saberduck** [comment]
@jblievremont sorry, I didn't see your comments here before. Imo, WHY is clear - we want to provide a more robust and secure analyzer. Sharing the common architecture will enable us to achieve that.
