### ISSUE TITLE
Provide to sonarlint correct metadata for the rule scope 

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#3122]
Currently it's all 'MAIN', SL for VS will need this data to be correct

**Comment by francoismora** [comment]
The scope is always MAIN in sonarlint-metadata.json because:

1. The sonar-analyzer-commons method RuleMetadataLoader.setMetadataFromJson() doesn't set the scope property when reading the JSON file.
2. The value is set to MAIN by default in the sonar-plugin-api DefaultRule constructor.
3. The rules, once loaded, are read-only, and the only place where we can set the scope is in RuleMetadataForSonarLint before populating the rules instance variable.

So this PR proposes to override the scope value for all rules by reading the JSON files a second time before populating the rules instance variable.

The EslinBasedCheck class also provides a method targets we could use. But it is defined in 1 class only (InvertedAssertionArgumentscheck). That's why this PR doesn't follow this approach.

The sonar-analyzer-commons code:
![image](https://user-images.githubusercontent.com/108535395/185360860-b18e3519-8339-4ede-b05f-9b74962e2ae9.png)
