### ISSUE TITLE
Eslint-bridge should not use too long paths

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#3135]
SonarLint is bundling eslint-bridge in Visual Studio. On Windows by default, there is a limit on the length of the path in the filesystem - 260 characters. Some of the dependencies of eslint-bridge are deeply nested, so extraction can fail.

This could be improved by using a bundler, such as ncc https://github.com/vercel/ncc

See also work by Andrea in https://github.com/SonarSource/SonarJS/issues/2520

**Comment by ilia-kebets-sonarsource** [comment]
The issue on SonarLint VS: https://github.com/SonarSource/sonarlint-visualstudio/issues/3011

**Comment by ilia-kebets-sonarsource** [comment]
## Why

SonarLint (SL) for Visual Studio (VS) fails to install on some dev environments that have a limit of file path length of around 260 characters. Depending on the username and eslint-bridge file paths, files of the eslint-bridge can lead to overflowing this limit. This limit was breached when SL tried to use SonarJS 8.9 that had a long dependency of ~260 chars: https://github.com/SonarSource/sonarlint-visualstudio/issues/3011

The eslint-bridge in SL gets installed at:

```
C:\Users\USERNAME\AppData\Local\Microsoft\VisualStudio\17.0_022f5ca6Exp\Extensions\SonarSource\SLAF\6.8.0.0\ts\
```

The path length is 103 chars long + the length of the username. If we reserve 37 chars for the username, it makes the base path 150 chars long, which leaves eslint-bridge 260-140=120 chars long for eslint-bridge filepaths.

## What

We investigate different ways to limit the filepath lengths inside the SonarJS distribution, especially the ones in eslint-bridge, which have long paths in dependencies.

After checking the current filepath lengths, we notice that the longest is at 118 characters from the `eslint-bridge/` folder, which is acceptable.

## How

We investigate mainly 2 paths for limiting the filepath length of our distribution: **flatten dependencies** and **bundling**.

### Flatten dependencies

#### NPM

npm offers `npm dedupe` which changes a single package, thus not offering the wanted improvement.

#### Yarn

yarn offers `yarn install --flat` which requires the user to choose a single version for each package to install at the root of `node_modules/`. We have multiple dependencies which require different major versions of the same package. After trying it a single time, launching the test suite failed as expected.

#### PNPM

pnpm failed as well.

For these reasons, dependency flattening proved useless in our case.

### Bundling

We have tested multiple tools that produced bundles that crashed at boot: @vercel/ncc, parcel, browserify, esbuild. We investigated more `ncc` which used to work up to SonarJS 8.2 (including), which broke with commit [2390015d46e](https://github.com/SonarSource/SonarJS/commit/2390015d46e0f8b5e8328a648d94537421d6ce10).
Therefore we confirm that bundling is quite unstable, as it can break with a minor depdendency update (here updating @babel/core from 7.13 to 7.15).

We started investigating `webpack` directly, since it's the most used bundler in JS and the one used by `ncc` under the hood. We believe that `ncc` broke because of a dynamic import used in the updated version of babel which failed on SonarJS 8.3 (https://github.com/vercel/ncc/issues/935). 
So it could be fixed by forcing the loading of libraries that might be missed.

For this, we need to make the following work:
- Force libs that are missed by the bundle to be included in it
- Figure out if we use TS or JS as entrypoint
- Make TS module aliases work

### Check

If we keep the filepath length under an acceptable maximum, we can postpone bundling until our dependencies require us to take action. After discussing with SL, we have proposed a max filepath length of 120.

**We can implement a check on the build script which will alert us if this filepath length limit is broken,** so we can take action before releasing.

Something like that run after `npm run jar`:

```bash
# This value was decided with SonarLint
MAX_FILEPATH=120

LONGEST_FILEPATH=$(tar tfz target/classes/eslint-bridge-1.0.0.tgz | awk '{print length($0), $0}' | sort -nr | head -n 1)
LONGEST_LENGTH=$(echo $LONGEST_FILEPATH | grep -o -E "[0-9]+")

if $LONGEST_LENGTH > $MAX_FILEPATH; then
	echo "File length is too long"
	# throw some visible warning
	return 1
else
	return 0
fi
```
