### ISSUE TITLE
Fix FP in S1117 - Variables should not be shadowed

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#3242]
Rule S1117 - Variables should not be shadowed

- Should be ignored for parameters of arrows functions with a single expression that are passed to array methods filter, map, find, etc.
- We should consider ignoring all parameters for single expression arrow functions.
- We should consider ignoring cases where the shadowed variable is hoisted, meaning it is defined after the shadow's definition.

**Comment by vilchik-elena** [comment]
I would consider challenging this rule in the first place, which kind of value we want it to bring? May be we should remove it from default profile without applying these changes as they seem to be pretty consuming.

**Comment by ilia-kebets-sonarsource** [comment]
As someone who likes internal functions, I do this a lot since I like to pass arguments as parameters explicitly instead of using the fact that they're in the same scope, like here the parameters `pair` and `ancestors`: https://github.com/SonarSource/SonarJS/blob/master/eslint-bridge/src/yaml/aws.ts#L70
