### ISSUE TITLE
Fix FP in S1172  Unused function parameters should be removed

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#3243]
S1172  Unused function parameters should be removed

- Should ignore preceding arguments when one argument has been used. For example, given a signature (a, b, c), when c is being used, a and b must be ignored.

**Comment by vilchik-elena** [comment]
I don't agree here, if `a` and `b` are  not used then they should be renamed into `_a` and `_b` to be explicit. @gabriel-vivas-sonarsource wdyt?

**Comment by gabriel-vivas-sonarsource** [comment]
As discussed together with @vilchik-elena we can remove the rule from the Sonar Way profile altogether.
TypeScript users would be covered by the TypeScript compiler (TS6133) and JavaScript users can still enable this rule when desired.

**Comment by saberduck** [comment]
@gabriel-vivas-sonarsource @vilchik-elena the rule was added to the profile quite recently in https://github.com/SonarSource/rspec/pull/917 , why was it added in the first place?

**Comment by yassin-kammoun-sonarsource** [comment]
@saberduck The activation ticket https://github.com/SonarSource/SonarJS/issues/2998 which links to the reason for this change https://github.com/SonarSource/SonarJS/issues/1832

**Comment by gabriel-vivas-sonarsource** [comment]
As I understand, it was added since we had it for TypeScript already and it seemed harmless to add it to JavaScript too.

However, we now know that the rule produces almost twice as much findings in JS projects than in TS projects.
Also, this rule is the No. 2 rule that produces most findings overall, of all the rules we have.
But for that much findings, the value can be challenged.
