### ISSUE TITLE
Deprecate formatting rules

### ISSUE THREAD

**Issue by gabriel-vivas-sonarsource** [SonarSource/SonarJS#3441]
## Why
We think source code formatting is better handled by a dedicated formatter like Prettier.
Since this is not our focus, we have little chance to provide more value than auto-formatting tools.
Automated formatters also tend to be opinionated, this removes disputes about which rules to use or not.
Formatting is also now available in most IDEs, so poor formatting never gets committed.
Removing this rules can improve analysis speed and increase our bandwidth to handle more relevant rules.

## What
Any rules we have about formatting, we want to deprecate them for this SQ LTS.
We also need to ensure that none of these rules are in the "Sonar Way" profile.

Within scope:
* Rules about a way to format code
* Any rule that is handled by Prettier
* Any rule that might conflict with Prettier

Out of scope:
* **Style changes that have semantic implications**
* Rules that enforce limits in code, For example:
* Number of parameters per function
* Number of lines per method
* Number of lines per file

## How
Let's try to list here all the rules that we need to deprecate.

**Comment by ilia-kebets-sonarsource** [comment]
From https://rules.sonarsource.com/javascript

### quickfixes:
- 3972 Conditionals should start on new lines
- 125 Sections of code should not be commented out
- 3863 Imports from the same modules should be merged
- 1940 Boolean checks should not be inverted
- 1128 Unnecessary imports should be removed
- 1116 Extra semicolons should be removed
- 3353 Unchanged variables should be marked "const"
- 1172 Unused function parameters should be removed
- 3512 Template strings should be used instead of concatenation
- 3498 Object literal shorthand syntax should be used
- 1537 Trailing commas should not be used
- 1488 Local variables should not be declared and then immediately returned or thrown
- 1441 Quotes for string literals should be used consistently
- 1438 Statements should end with semicolons
- 1131 Lines should not end with trailing whitespaces
- 113 Files should contain an empty newline at the end
