### ISSUE TITLE
Fix FP S1128 (`unused-imports`): Vue.js imports used in templates

### ISSUE THREAD

**Issue by ilia-kebets-sonarsource** [SonarSource/SonarJS#3484]
The script attribute `lang="ts"` is necessary for this FP to occur.

```javascript
<template>
  <Foo />
</template>

<script setup lang="ts">
import Foo from './Foo' // FP
</script>
```

Reported in:
- https://community.sonarsource.com/t/remove-this-unused-import-of-xxx-rule-is-not-detecting-them-in-template-vue-js/74330
- https://community.sonarsource.com/t/false-postive-javascript-s1128-with-vue-script-setup-lang-ts/73990
- https://community.sonarsource.com/t/vue3-composition-api-and-script-setup-syntax-reports-unused-imports-since-october-22/74614

**Comment by Zorin95670** [comment]
Also appear, if we are not on TS script :)
Example with no TS script : https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=ditrit_leto-modelizer&open=AYOJrJ45O7ogrcn3JpkB

**Comment by ilia-kebets-sonarsource** [comment]
Thanks for notifying us @Zorin95670. The current fix does also fix the issue you linked to.

**Comment by ferferga** [comment]
@ilia-kebets-sonarsource 
Hello, sorry for necropost, but I've been following this issue since it was created because I'm affected. I've been tracking it until the day of it being closed and since it's not very old, I think it's better than opening a new issue.

The issue it's not solved for me. I've kept waiting and waiting (just to see if Sonar somehow needed to flush its cache or "refresh" itself), but still no luck, even after modifying the affected files directly.

Not sure if it's relevant, but my imports are not default ones, like this: `import { Swiper } from 'swiper/vue';`

**Comment by ilia-kebets-sonarsource** [comment]
Hey @ferferga,

Could you provide a more elaborate code example of how you use your component and where is the issue raised?

**Comment by ilia-kebets-sonarsource** [comment]
Can you please report this under the relevant product at https://community.sonarsource.com/ ?
