### ISSUE TITLE
Remove S6480 from default profile

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#3614]
We need to improve documentation before including this rule in LTS

**Comment by AndersonHqds** [comment]
Yeah, sonarcloud is forcing the react applications using the `useCallback` for all functions, and it should not be used for all of them.

**Comment by ls-yannick** [comment]
I'm not sure if this is on your radar as well, but applying useCallback without a `memo()` on the called component won't actually improve performance, but the extra useCallback+dependencies will arguably hurt readability of the code. The new react docs [have a pretty comprehensive section about this](https://beta.reactjs.org/reference/react/useCallback#skipping-re-rendering-of-components).

**Comment by gabriel-vivas-sonarsource** [comment]
Adding related Community thread for historic context:
https://community.sonarsource.com/t/6480-validation-typescript-code-smell/78668/6

**Comment by gabriel-vivas-sonarsource** [comment]
@ls-yannick thanks for the link.

Indeed, `memo` of direct children is the prominent use case.
Unfortunately, there are more subtle cases that are hard to track.

For example, when the function is used as a Hook dependency lower in the tree, it will trigger the hook.
Also, when passed to grand-child components, it will invalidate any memoization there.

Anyway, we are good listeners, so we are removing it from the "Sonar Way" until we can learn more about user's expectations for this.

Most probably, we will need to improve the rule before it comes back to the spotlight.

**Comment by MaelthiS** [comment]
@gabriel-vivas-sonarsource do you know if users of Sonar cloud have something manually to do to disable the rule ? Or the sonar way quality profile will update by itself ? Because we still have the issue on new code in our repo.

**Comment by gabriel-vivas-sonarsource** [comment]
Hi @MaelthiS, it should be automatic if you're using the Sonar Way profile in SonarCloud

**Comment by ls-yannick** [comment]
Same here btw, it still hasn't come through.

**Comment by rubenmamo** [comment]
Same here as well, I still see these errors on my scans

**Comment by gabriel-vivas-sonarsource** [comment]
Sorry for the confusion, we removed from SonarQube LTS before release, it will be updated in SonarCloud soon.
If you need this now, you can create a new profile that inherits from Sonar Way and disable the rule.
Otherwise, hang on, it should be transparent.

**Comment by lebbe** [comment]
We still are hassled by it in Sonar Cube.

Would be nice with some transparency around the introduction of this rule in the first place. Because when I first noticed this rule, it went against all my instincts with regard to premature optimization versus readable code. What team in Sonar discussed this, and landed in the rule being a clever thing to introduce in the first place?

I've already seen applications in havoc with hundreds of "useCallback" statements, in an attempt to oblige this lint rule. The developers feed lambdas to useCalkback, initialize a const with the return value and send this as an property.  I wouldn't be surprised if this is more computationally expensive than just sending the lambda in the first place. I _know_ that the code is much less readable.

I don't think this rule should be removed from the default, or have a better documentation. I think the rule should be nuked from existence.

**Comment by ilia-kebets-sonarsource** [comment]
Hello,
For the default profile to reflect this change, you need to upgrade your SonarQube instance to at least version 9.9.
