### ISSUE TITLE
Support ESLint 9 config format (flat config)

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#3968]

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-91

**Comment by bmulholland** [comment]
@Wohops How do we now watch the issue so we get alerted when it's resolved?

**Comment by what1s1ove** [comment]
> @Wohops How do we now watch the issue so we get alerted when it's resolved?

Agreed!

**Comment by Wohops** [comment]
Hello @bmulholland , @what1s1ove ,

Unfortunately, we are aware that it is not possible to watch Jira issue for the time being.
I feel that for the time being, you will have to visit the ticket regularly to check its status.

Michael

**Comment by carlosnavaja16** [comment]
The issue is closed on Jira and here yet it seems like the flat config is still not supported. When try setting up the config following the docs:

`
[
  sonarjs.configs.recommended,
  {
    "plugins": {
      sonarjs,
    }
  }
]
`
I get the following error:
`Config "@navaja/eslint-config": Key "plugins": Cannot redefine plugin "sonarjs"`

**Comment by EmilyRagan** [comment]
I'm now seeing that the Jira issue has been moved to status "Canceled" as of October 29. Is this accurate? I am getting the same error as @carlosnavaja16
