### ISSUE TITLE
Error version 3.0

### ISSUE THREAD

**Issue by aaschlote** [SonarSource/SonarJS#4985]
Hello all,

after update the version 3.0, I'm getting the following error:

```
ESLint: 9.14.0

TypeError: Key "rules": Key "sonarjs/jsx-no-constructed-context-values": Could not find "jsx-no-constructed-context-values" in plugin "sonarjs". Did you mean "react/jsx-no-constructed-context-values"?
```

You can see more details in the following [link](https://github.com/digitalservicebund/a2j-rechtsantragstelle/actions/runs/12137079330/job/33839519979).

And a few links on the [release page](https://github.com/SonarSource/SonarJS/releases/tag/3.0-RC1) are not working:

[Link](https://docs.sonarsource.com/sonarqube-server/display/PLUG/Custom+Rules+for+SonarJS#CustomRulesforSonarJS-SonarJS3.0trueYellowBETA)
<img width="1457" alt="image" src="https://github.com/user-attachments/assets/5e0ad07c-fabd-4445-a908-2ccd5de4fb73">

[Link](https://sonarsource.atlassian.net/secure/ReleaseNote.jspa?isRedirectedFromLegacy=true&projectId=10933&version=13050)
<img width="1268" alt="image" src="https://github.com/user-attachments/assets/6d77a020-608c-4d57-902e-64b46ae996c6">

**Comment by ajslater** [comment]
With no release notes available since the merge to the monorepo and a major version change, there are probably lots of breaking changes catching users unaware.

In my own use sonarjs 3.0 breaks eslint-plugin-import configuration making it unable to find the vue-eslint-parser module. I've not yet divined why this happens, so I'll be staying on eslint-plugin-sonarjs 2.0.4 until more clarity is provided.

**Comment by silverwind** [comment]
Seems it's time to drop`eslint-plugin-sonarjs`. No release notes, not docs and I can't even find where the npm package is published from in this repo.

**Comment by vdiez** [comment]
Hello all,

@aaschlote, those release notes are from SonarJS 3.0.0 from 2017, the JS/TS analyzer contained in SonarQube. The `eslint-plugin-sonarjs` follows different versioning.

@silverwind @ajslater As for the changelog, we just added a new [CHANGELOG.md](https://github.com/SonarSource/SonarJS/blob/master/packages/jsts/src/rules/CHANGELOG.md) mentioning the changes specific to the ESLint plugin. On the npm page, you can see that the homepage for the ESLint plugin is [here](https://github.com/SonarSource/SonarJS/blob/master/packages/jsts/src/rules/README.md).

3.0.0 was a major release because we removed many rules that were modified from external plugins (those were all added in 2.0.0). We decided that from now on, we will only publish rules that are our own implementation in the ESLint plugin. Otherwise, we were tightly coupled with specific versions of `typescript-eslint` and other dependencies that clashed with our users' dependencies versions. The new README.md mentions this [here](https://github.com/SonarSource/SonarJS/blob/master/packages/jsts/src/rules/README.md#eslint-rules) and [here](https://github.com/SonarSource/SonarJS/blob/master/packages/jsts/src/rules/README.md#improved-eslint-rules).

@aaschlote the rule of the error ("sonarjs/jsx-no-constructed-context-values") is one of those rules that we've decided not to include. In the README you can see that the rule you should use now is [react/jsx-no-constructed-context-values](https://github.com/jsx-eslint/eslint-plugin-react/blob/HEAD/docs/rules/jsx-no-constructed-context-values.md).

@ajslater Can you share details about what error are you getting in the import plugin?

**Comment by silverwind** [comment]
Thanks, looks good. I will check if I can upgrade to v3.
