### ISSUE TITLE
Retrieve metadata from package.json

### ISSUE THREAD

**Issue by AMorgaut** [SonarSource/SonarJS#897]
**I want to request a feature.**

It is probably more related to `sonar-scanner`, but the `package.json` file is quite JavaScript projects specific which is why I post it here.

When running `sonar-scanner`, it use configuration defined in `sonar-project.properties`, overridden by its arguments

It is very redundant to copy all the data (project name, author, description, urls) from `package.json` to `sonar-project.properties`. It would facilitate the **getting started** with sonar on JS projects if it could natively read them from there.

Where it would be even better is regarding the **version number**. It could then be automatically in sync.

**Comment by vilchik-elena** [comment]
@AMorgaut https://www.npmjs.com/package/sonarqube-scanner is doing exactly what you are asking for.

**Comment by adrianovieira** [comment]
I'm also having this issue here. 

@vilchik-elena,
I created a new project in SonarQube-7.4. So, it recommended to Download (`sonar-scanner`) from -> _SonarQube Scanner 3.2_ on https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner

After installing it the folowing basic comand needs to be executed:

```
sonar-scanner \
  -Dsonar.projectKey=nodejssample-api \
  -Dsonar.sources=. \
  -Dsonar.host.url=http://sonar.devops \
  -Dsonar.login=ea8eff40c6f79569a03810acdba76e7e098d5e49
```

with this basic command, that latest `sonar-scanner` version don't read parameters value from **package.json** of a Node.js application.

How could I setup that `sonar-scanner` cli to read `package.json`?
